apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
