apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask-hello-container
        image: somyanegi/node-hello:day1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "60Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "250m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
